version: '3'

services:
  apache:
    build:
         context: ./php
         dockerfile: Dockerfile
    
    container_name: php
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./php:/var/www/html
    depends_on:
      - db
    links:
      - db  
  db:
    image: mysql:5.7
    command: --init-file /init.sql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
             - ./init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trabalho
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "6033:3306"
 
