CREATE DATABASE IF NOT EXISTS trabalho;
CREATE TABLE IF NOT EXISTS login (
        LOG_ID INT NOT NULL AUTO_INCREMENT,
        LOG_USUARIO VARCHAR(50),
        LOG_SENHA VARCHAR(50),
        CONSTRAINT ID_PK PRIMARY KEY (LOG_ID)
);

commit;
